# Generated by Django 3.1.4 on 2021-01-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210106_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_published',
        ),
    ]
